
// CATEGORIES
export const SHOW_CATEGORY_FORM = 'SHOW_CATEGORY_FORM'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'

// CURRENT CATEGORY
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'
export const CLEAR_CURRENT_CATEGORY = 'CLEAR_CURRENT_CATEGORY'

// TODOS
export const ADD_TODO = 'ADD_TODO'
export const CHECK_TODO = 'CHECK_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'
export const UPDATE_MULTIPLE_TODOS = 'UPDATE_MULTIPLE_TODOS'
export const DELETE_TODO = 'DELETE_TODO'
export const DELETE_MULTIPLE_TODOS = 'DELETE_MULTIPLE_TODOS'

// CURRENT TODO
export const SET_CURRENT_TODO = 'SET_CURRENT_TODO'
export const CLEAR_CURRENT_TODO = 'CLEAR_CURRENT_TODO'